; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.16 on Tue May 23 2023 16:07:45 GMT+0200 (Central European Summer Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


